config/routes.rb
Rails.application.routes.draw do

  resources :post, shallow: true do
    resources :comment
  end

  get 'posts/index'

  post '/posts/create', to: 'posts#create', as: 'post_create'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
	belongs_to :user
	acts_as_votable
	accepts_nested_attributes_for :comments, allow_destroy: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts, dependent: :destroy
	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comment = Comment.all
  end

  def new
    @comment = Comment.new
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def edit
  end
  
  def create
  @comment = Comment.create(comment_params)
    redirect_to :action => "index"
  end

  def comment_params
    params.require(:comment).permit(:body)
  end

  # def create
  # 	@post = Post.find(params[:post_id])
  # 	@comment = @post.comments.create(params[:comment])
  # 	@comment.user_id = current_user.id
  # 	if @comment.save
  # 	redirect_to post_path(@post)
  #   else
  #   	flash.now[:danger] = "error"
  # end

  def comments
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
  	@posts = Post.all
    @post = Post.new
    comment = @post.comments.build
  end

  def show
    @post=Post.find(params[:id])
  end

  def edit
  end

  def new
  	@post = Post.new
  end

  def create
    @post = Post.create(post_params)
    comment = @post.comments.first #
    comment.user = User.last # assign comment to user
    comment.save
    redirect_to :action => "index"
  end

  def post_params
    params.require(:post).permit(:description, comments_attributes:[:body])
  end

  def upvote
    @post = Post.find(params[:id])
    @post.upvote_by current_user
    redirect_to links_path
  end

  def down_votes
    self.votes.where(value: -1).count
  end  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def update
  end

  def delete
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rubyedu</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<h2> RubyEdu.com - Our favorite Ruby education material </h2>
<h3> プログラマキャパ確保 </h3>
<h3> 石井プロジェクト拡充 </h3>
<h3> incubatefundピボット後のドキュメント </h3>
<h3> jafco起業家イベント </h3>
<h3> 1000万円留衣ブレスト </h3>
<br> 

<% @posts.each do |post| %>
<p>

<td><%= post.description %></td>
<td><%= form_for post do |f| %></td>
  <td>Description: <%= f.text_area :description %><br /></td>
   <%= f.fields_for :comments do |comment| %>
   <td>Comment: <%= comment.text_area :body %> <br></td>
<% end %>
<% end %>
</p>
<% post.comments.each do |comment| %>
<p>
comment: <%= comment.body %>
user: <%= comment.user.name if comment.user %>
published: <%= time_ago_in_words(comment.created_at) %>
</p>
<% end %>
<% end %>


<%= form_for @post, url: post_create_path do |f| %>
  Description: <%= f.text_area :description %><br />
   <%= f.fields_for :comments do |comment| %>
   Comment: <%= comment.text_area :body %> <br>
<% end %>

  <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<h2> RubyEdu.com - People's favorite Ruby educational material </h2>
<br>
<table>
  <tr>
    <td>description</td>
    <td>upvote</td> 
    <td>comment</td>
  </tr>
</table>

<% @posts.each do |f| %>
<%= f.description %>
<br>
<% end %>

<%= form_for :post, url: post_create_path do |f| %>
  Description: <%= f.text_area :description %><br />
  <%= f.submit %>
<% end %>

<%= form_for @post do |f| %>
  <%= f.fields_for :comments do |c| %>
    <%= c.text_field :title %>
  <%= f.submit %>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>